/** @deprecated Import from `../balance/career.js`. */
export {
	MOOD_MIN,
	MOOD_MAX,
	MOOD_NEUTRAL,
	WEEKLY_DRIFT,
	RACE_PODIUM_MORALE,
	RACE_POINTS_MORALE,
	RACE_BACKMARKER_MORALE,
	ORDER_OBEYED_MORALE,
	ORDER_SACRIFICED_MORALE,
	ORDER_REFUSED_LOYALTY,
	DIVISION_PAY_BASELINE,
	TOXIC_EGO_THRESHOLD,
	TOXIC_MORALE_HIT,
	TOXIC_LOYALTY_HIT,
	QUIT_MORALE_THRESHOLD,
	QUIT_LOYALTY_THRESHOLD
} from '../balance/career.js';
