/** @deprecated Import from `../balance/finance.js`. */
export {
	DIVISION_COST_CAP,
	MINOR_BREACH_MAX_OVERAGE,
	MINOR_BREACH_FINE_OF_OVERAGE,
	MAJOR_BREACH_FINE_OF_OVERAGE,
	MINOR_BREACH_WT_MULT,
	MAJOR_BREACH_WT_MULT,
	MAJOR_BREACH_POINTS_PENALTY,
	RD_WT_HOUR_CASH,
	RD_CFD_HOUR_CASH,
	TOP_STAFF_SALARY_EXEMPT,
	PAYROLL_WEEKS_PER_YEAR,
	CONSTRUCTORS_PRIZE_BY_DIVISION
} from '../balance/finance.js';
