/** @deprecated Import from `../balance/career.js`. */
export {
	WEEKLY_WT_CAP,
	WEEKLY_CFD_CAP,
	FACILITY_WEEKLY_DECAY,
	XP_PER_LEVEL,
	DRIVER_WEEKLY_XP_BASE,
	STAFF_WEEKLY_XP_BASE,
	XP_PER_MILEAGE_LAP,
	FATIGUE_RECOVERY_PCT,
	PACE_PHYSICAL_ATTRS,
	TIER_EFFICIENCY
} from '../balance/career.js';
