/** @deprecated Import from `../balance/lap.js` — re-export for call-site compatibility. */
export {
	ATTR_MULT_MIN,
	ATTR_MULT_MAX,
	REF_AERO_PP,
	REF_MECH_PP,
	REF_POWER_PP,
	CAR_PP_SCALE,
	SETUP_SWEET_SPOT,
	SETUP_PENALTY_K,
	FUEL_KG_TIME_FACTOR,
	REF_FUEL_BURN_KG_PER_LAP,
	PACE,
	ENERGY,
	TIRE_CLIFF,
	TIRE_PEAK_GRIP,
	TIRE_OPT_TEMP,
	TIRE_TEMP_WINDOW,
	CLIFF_PENALTY_K,
	MOISTURE_COMPOUND,
	DIRTY_AIR_PENALTY_K,
	DAMAGE_PENALTY_K
} from '../balance/lap.js';
